### ISSUE TITLE
Impossible to implement

### ISSUE THREAD

**Issue by latunoff** [VamOSGS/react-preloaders#1]
in render() should be only one element which contains anothers...
errors:
Module build failed: SyntaxError: D:.../src/App.jsx: Adjacent JSX elements must be wrapped in an enclosing tag
If I insert it inside another tag:
Error: Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type

**Comment by VamOSGS** [comment]
Fixed! (sorry I forgot to answer)
