### ISSUE TITLE
Ability to pass custom component as loader

### ISSUE THREAD

**Issue by krnareshkumar23** [VamOSGS/react-preloaders#12]
**Is your feature request related to a problem? Please describe.**
It is great that we have several preloader options provided with the package however certain apps require very custom loading screens to be displayed. Do you have plans to include them?

Also, do we have provision to custom style the loading components? say in planets, can we customise it to have additional planets and configure colour options to the same?

**Comment by VamOSGS** [comment]
Hi, thanks for issue, issues helping me make my package better.

Starting from version 3.x.x you can customize animation type, background and main color of component by passing props to Preloader component. About customizing preloaders you can read **[here](https://github.com/VamOSGS/react-preloaders#properties-props)**.

Starting from version 3.x.x you can use your components as preloader, but info about this missing in docs. It's my mistake and I will write about this in docs.

Here is example how you can use your component as prelaoder:

```jsx
import React from 'react';
import { CustomPreloader } from 'react-preloaders';

function App() {
  return (
    <React.Fragment>
      <YourApp />
         <CustomPreloader>
                 YOUR CUSTOM PRELOADER
         </CustomPreloader>
    </React.Fragment>
  );
}
```

**Comment by VamOSGS** [comment]
@krnareshkumar23 I already update [README](https://github.com/VamOSGS/react-preloaders/blob/master/README.MD#your-components-as-preloader) and add CustomPreloader usage in it.
