### ISSUE TITLE
Manually stop loading

### ISSUE THREAD

**Issue by sayhicoelho** [VamOSGS/react-preloaders#5]
The docs doesn't have any tips showing us on how to manually stop loading. For example, if we need to show the loading screen while some data from API is fetching and stop it after data is fetched, how to do this?

Currently its impossible to implement?

Thanks!

**Comment by VamOSGS** [comment]
@sayhicoelho Thanks for issue) In this version of package its impossible, but I will try to add it in future versions.

**Comment by VamOSGS** [comment]
@sayhicoelho Its added in [react-preloaders v3.x.x](https://www.npmjs.com/package/react-preloaders) Thanks for issue
